os:
  - linux

script:
  - "docker-compose up --build -d dev"
  - "docker-compose exec dev ./build.sh"
  - "docker-compose exec dev echo \"Running imaginary tests\""
  - "docker-compose down"

deploy:
  skip_cleanup: true
  provider: script
  script: bash docker_push.sh
  on:
    branch: release/1.11-aviata

# Encrypted Docker Hub password
env:
  global:
    secure: "ToGZ5r8JlS3zo0FQ/xRxwD06O+9HsRjoYGBnHOoqvtstwERv37cH2ZxOHVEN8jBiAb4rGAjMAHoFeQMjYfO07rmNtyq4IRL21MpzzUeHk6ozzis2VXED0UnCEg+WqktKl7u8Wo+AIa+18fJ5zi2795Va5uoaqDb6xxc1o2NmNoqvQKiJIuzo4+eJAbfNcf5l14ldOkswFOb/kTyzXxagkIvuYSh4FyAn/mJtCD4+/yhd01x4S+RTqdwUaO28yqgpsQe8KV9BxZ2xyHqLNB28HH5vhu3lNcXUoYvSOoPDwjGvtCwVchBQgwO5pyDT94ajAZEfT/FSlLlzJk7AoK+x0ExPcgdicGgxcDPMLMShSue/2Yz3Vq9YaFCWI0PNIfgNd6XTi3LX42kHJkzekw5nssQqbuvCg7swLARCJUrDIB/Q81KSgv6mWB7ra8oyMpcRQxQUjxfL7HpX0U2PyKAG/JEDTbkgbpCMkoJwRAjzQYIKLv+ZPBqv0cqgbjHmXfXykC9VsrMMqwTns0qNAdOejATcOoTi1pubzOp2FOVzFUJXHXiVMmn+oJACsqqObc6lup0IFmNrc7rm+PQRkDAqipWY/fdORtF3rIdkTdM8NDC94oGic6LSiaYQV4EEE3PTc3q37JHiqAM6kaq42pVouczz5XDWnqQmG4eGvXH26z4="
